---
- hosts: all
  gather_facts: true
  ignore_errors: true
  tasks:
  - name: Run multiple commands on remote nodes
    alcatel.aos8.aos8_command:
      commands:
        - show system 
        - show ip interface
