---
- hosts: all
  gather_facts: true
  ignore_errors: true
  tasks:
    - name: Run aos_hostname merged
      alcatel.aos8.aos8_hostname:
        config:
          hostname: R1
        state: merged

