---
- hosts: all
  gather_facts: true
  ignore_errors: true
  name: VLAN delete with flash_synchro (true)
  vars:
    ansible_aos_flash_synchro_flag : true
  tasks:
    - name: Run VLAN resource module with state deleted
      alcatel.aos8.aos8_vlans:
        config:
          - vlan_id: 33
          - vlan_id: 99
        state: deleted
